pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f tom-jen/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'tomcat-deploy'

            }
            
        }
       
    }
}
